comment out initcontainer

diff --git a/sam-deployment.yml b/sam-deployment.yml
--- a/sam-deployment.yml
+++ b/sam-deployment.yml
@@ -15,23 +15,23 @@ spec:
         app: sam
         version: 'v1'
     spec:
-      initContainers:
-        - name: init-ds
-          image: busybox:latest
-          command:
-            - '/bin/sh'
-            - '-c'
-            - |
-              while true
-              do
-                rt=$(nc -z -w 1 10.105.61.185 5432)
-                if [ $? -eq 0 ]; then
-                  echo "DB is UP"
-                  break
-                fi
-                echo "DB is not yet reachable;sleep for 10s before retry"
-                sleep 10
-              done
+      # initContainers:
+      #   - name: init-ds
+      #     image: busybox:latest
+      #     command:
+      #       - '/bin/sh'
+      #       - '-c'
+      #       - |
+      #         while true
+      #         do
+      #           rt=$(nc -z -w 1 10.105.61.185 5432)
+      #           if [ $? -eq 0 ]; then
+      #             echo "DB is UP"
+      #             break
+      #           fi
+      #           echo "DB is not yet reachable;sleep for 10s before retry"
+      #           sleep 10
+      #         done
       containers:
         - name: sam-app
           image: antphungit/sam
